name: TestBuild

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: try to build
      - uses: actions/checkout@v4

      - name: setup.dotnet
        uses: actions/setup-dotnet@v4.1.0
        with: 
          dotnet-version: '8.0.10'
      - name: build
        run: | 
          cd todo
          dotnet build todo.csproj
