name: TestBuild

on: workflow_dispatch


jobs: 
  build-project: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .net
      uses: actions/setup-dotnet@v4.1.0
      with: 
        dotnet-version: 9
    - name: Build project
      run: cd todo; dotnet build
