name: TestBuild

on:
  push:
    paths:
      - '**/*.cs'


jobs: 
  build-project: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .net
      uses: actions/setup-dotnet@v4.1.0
      with: 
        dotnet-version: 8
    - name: Build project
      run: cd todo; dotnet build
