name: Dev tododemo

on: workflow_dispatch

jobs: 
  print-reponame:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get repository name only
      run: |
        REPO_NAME=${GITHUB_REPOSITORY##*/}
        echo "Repository Name: $REPO_NAME"
        
  print-currentbranch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get current branch
      run: GITHUB_REF_NAME
