name: staging

on:
  push:  
    branches:
      - staging
  pull_request:
    branches:
      - staging


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up dotnet
      uses: actions/setup-dotnet@v4.1.0
      with: 
        dotnet-version: 8
    - name: build project
      run: cd todo; dotnet build
    - name: publish project
      run: cd todo; dotnet publish

    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: todo/bin/Debug/net8.0/publish
        path: home/runner/work/Dev-todo2/Dev-todo2/todo/bin/Release/net8.0/publish/
    
        
