name: demo of variables and context

on: workflow_dispatch

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build project
      run: dotnet build

  context:
    runs-on: unbuntu-latest
    steps:
    - name: get github context info
      run: echo ${{toJSON(github)}}
    - name: get repo name
      run: echo ${{github.repository}}
