name: demo of variables and context

on:  
  workflow_dispatch:
    inputs:
      should_fail:
        description: "shall fail if input < 7"
        required: true
        type: int
        default: '0'
 
   

jobs:

#det här ett jobb
  build:
    runs-on: ${{ matrix.os }}
    if: always()
    strategy: 
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ 8.0, 7.0, 6.0 ]

    steps:
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        version: ${{matrix.os}}

        
  # det här ett annat jobb
  build-project:
    runs-on: ubuntu-latest
  
    env:
      passing_score: 7
      job_env_variabels: "this is jobs level enviroment variabel"
   
    steps:
     
      - name: steps that can fail
        env:
         step_Level_env: "this is step level env variabel"
        run: |
          echo "failcheck..."
          input_value=$(expr "${{ github.event.inputs.should_fail }}" + 0)
          if [ "$input_value" -lt "$passing_score" ]; then
            exit 1
          fi
      - uses: actions/checkout@v4
      
      - name: print jobs enviroment
        if: always()
        run: echo "$job_env_variabels"

      - name: print steps enviroment
        if: always()
        run: echo "$step_Level_env"
        
      - name: Build project
        run: dotnet build
      
      - name: Get GitHub context info
        run: echo "${{ toJSON(github) }}"
      
      - name: Get repository name
        run: echo "${{ github.repository }}" 


  
