name: demo of variables and context

on:   workflow_dispatch


jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
          
      - uses: actions/checkout@v4

      - name: Build project
        run: dotnet build

      - name: Get GitHub context info
        run: echo "${{ toJSON(github) }}"

      - name: Get repository name
        run: echo "${{ github.repository }}" 
